apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api
        image: iris-api:latest  # Replace with your image repo if pushing to a registry
        ports:
        - containerPort: 8000
        env:
        - name: API_KEY
          value: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  selector:
    app: iris-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 