dbt_spark_profile:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: localhost
      port: 10001
      user: your_user
      database: default
      threads: 1
      connect_retries: 1
      retry_all: true
      use_ssl: false