name: 'dbt_spark_example'
version: '1.0.0'
config-version: 2

profile: 'dbt_spark_profile'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
analysis-paths: ['analyses']
macro-paths: ['macros']
target-path: 'target'
clean-targets: ['target', 'dbt_modules']

models:
  dbt_spark_example:
    staging:
      materialized: view
    marts:
      materialized: table